### ISSUE TITLE
Getting Class not found exception

### ISSUE THREAD

**Issue by sweta01** [hendraanggrian/collapsingtoolbarlayout-subtitle#19]
Landroid/support/v4/math/MathUtils

 java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v4/math/MathUtils;
                                                                 at android.support.design.widget.SubtitleCollapsingToolbarLayout$OffsetUpdateListener.onOffsetChanged(SubtitleCollapsingToolbarLayout.kt:672)
                                                                 at android.support.design.widget.AppBarLayout.dispatchOffsetUpdates(AppBarLayout.java:468)
                                                                 at android.support.design.widget.AppBarLayout$Behavior.setHeaderTopBottomOffset(AppBarLayout.java:1160)
                                                                 at android.support.design.widget.AppBarLayout$Behavior.setHeaderTopBottomOffset(AppBarLayout.java:766)
                                                                 at android.support.design.widget.HeaderBehavior.setHeaderTopBottomOffset(HeaderBehavior.java:194)
                                                                 at android.support.design.widget.AppBarLayout$Behavior.onLayoutChild(AppBarLayout.java:1059)
                                                                 at android.support.design.widget.AppBarLayout$Behavior.onLayoutChild(AppBarLayout.java:766)
                                                                 at android.support.design.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:870)
                                                                 at android.view.View.layout(View.java:16024)
                                                                 at android.view.ViewGroup.layout(ViewGroup.java:5243)
                                                                 at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1195)
                                                                 at android.view.View.layout(View.java:16024)
                                                                 at android.view.ViewGroup.layout(ViewGroup.java:5243)
                                                                 at android.widget.FrameLayout.layoutChildren(FrameLayout.java:639)
                                                                 at android.widget.FrameLayout.onLayout(FrameLayout.java:574)
                                                                 at android.view.View.layout(View.java:16024)
                                                                 at android.view.ViewGroup.layout(ViewGroup.java:5243)
                                                                 at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1195)
                                                                 at android.view.View.layout(View.java:16024)
                                                                 at android.view.ViewGroup.layout(ViewGroup.java:5243)
                                                                 at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1195)
                                                                 at android.view.View.layout(View.java:16024)
                                                                 at android.view.ViewGroup.layout(ViewGroup.java:5243)
                                                                 at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1195)
                                                                 at android.view.View.layout(View.java:16024)
                                                                 at android.view.ViewGroup.layout(ViewGroup.java:5243)
                                                                 at android.support.design.widget.CoordinatorLayout.layoutChild(CoordinatorLayout.java:1167)
                                                                 at android.support.design.widget.CoordinatorLayout.onLayoutChild(CoordinatorLayout.java:852)
                                                                 at android.support.design.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:871)
                                                                 at android.view.View.layout(View.java:16024)
                                                                 at android.view.ViewGroup.layout(ViewGroup.java:5243)
                                                                 at android.support.v4.widget.DrawerLayout.onLayout(DrawerLayout.java:1193)
                                                                 at android.view.View.layout(View.java:16024)
                                                                 at android.view.ViewGroup.layout(ViewGroup.java:5243)
                                                                 at android.widget.FrameLayout.layoutChildren(FrameLayout.java:639)
                                                                 at android.widget.FrameLayout.onLayout(FrameLayout.java:574)
                                                                 at android.view.View.layout(View.java:16024)
                                                                 at android.view.ViewGroup.layout(ViewGroup.java:5243)
                                                                 at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1959)
                                                                 at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1813)
                                                                 at android.widget.LinearLayout.onLayout(LinearLayout.java:1722)
                                                                 at android.view.View.layout(View.java:16024)
                                                                 at android.view.ViewGroup.layout(ViewGroup.java:5243)
                                                                 at android.widget.FrameLayout.layoutChildren(FrameLayout.java:639)
                                                                 at android.widget.FrameLayout.onLayout(FrameLayout.java:574)
                                                                 at android.view.View.layout(View.java:16024)
                                                                 at android.view.ViewGroup.layout(ViewGroup.java:5243)
                                                                 at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1959)
                                                                 at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1813)
                                                                 at android.widget.LinearLayout.onLayout(LinearLayout.java:1722)
                                                                 at android.view.View.layout(View.java:16024)
                                                                 at android.view.ViewGroup.layout(ViewGroup.java:5243)
                                                                 at android.widget.FrameLayout.layoutChildren(FrameLayout.java:639)
                                                                 at android.widget.FrameLayout.onLayout(FrameLayout.java:574)
                                                                 at android.view.View.layout(View.java:16024)
                                                                 at android.view.ViewGroup.layout(ViewGroup.java:5243)
                                                                 at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2555)
                                                                 at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2245)
                                                                 at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1342)
                                                                 at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6829)

**Comment by hendraanggrian** [comment]
What version of support library are you using?

**Comment by sweta01** [comment]
Now resolved

**Comment by hendraanggrian** [comment]
Great!

**Comment by sweta01** [comment]
The library is good.
